CREATE VIEW SPY_MA AS
WITH MA AS (
SELECT DATE,[CLOSE],
AVG([CLOSE]) OVER (ORDER BY DATE ROWS BETWEEN 49 PRECEDING AND CURRENT ROW) AS MA50,
AVG([CLOSE])  OVER (ORDER BY DATE ROWS BETWEEN 199 PRECEDING AND CURRENT ROW) AS MA200
FROM SPY_CLOSE_PRICE_5Y)
SELECT DATE,[CLOSE],MA50,MA200,
CASE
WHEN MA50 IS NULL OR MA200 IS NULL THEN 0
WHEN MA50>MA200 AND LAG(MA50) OVER (ORDER BY DATE) <= LAG(MA200) OVER (ORDER BY DATE) THEN 1
ELSE 0
END AS GOLDEN_CROSS
FROM MA;




SELECT TOP 1 DATE, [CLOSE]
FROM SPY_MA
WHERE GOLDEN_CROSS = 1
ORDER BY DATE DESC;