# -*- coding: utf-8 -*-
"""Olist Brazilian E-Commerce Delivery Performance and Customer Satisfaction Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12gQgRys_73E-zVdyWAoNYrEHWbdBVGjX

# Importing Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats  # for hypothesis tests (Mann-Whitney, chi-square, etc.)

sns.set_style("whitegrid")  # adds light grid lines to charts (cosmetic only)
plt.rcParams["figure.figsize"] = (10,6)   # default chart size, so we don't repeat it every time
pd.set_option("display.max_columns",50)     # show up to 50 columns instead of truncating with "..."

# consistent colors used across all charts in this report
color_good = "#4C72B0"   # blue, used for on-time / normal / baseline
color_bad = "#C44E52"    # red, used for late / problem / highlighted issue

"""### Loading the Dataset"""

from google.colab import drive
drive.mount('/content/drive')

DATA_DIR = "/content/drive/MyDrive/Python Project/Olist E-Commerce analysis/data/"

# To check all files have been uploaded or not
import os
print(os.listdir(DATA_DIR))

orders = pd.read_csv(DATA_DIR + "olist_orders_dataset.csv")  # main orders table: dates, status
items = pd.read_csv(DATA_DIR + "olist_order_items_dataset.csv")  # products + price + freight per order
payments = pd.read_csv(DATA_DIR + "olist_order_payments_dataset.csv")  # payment type, installments
reviews = pd.read_csv(DATA_DIR + "olist_order_reviews_dataset.csv")  # review score per order
customers = pd.read_csv(DATA_DIR + "olist_customers_dataset.csv")  # customer id + state
sellers = pd.read_csv(DATA_DIR + "olist_sellers_dataset.csv")  # seller id + state
products = pd.read_csv(DATA_DIR + "olist_products_dataset.csv")  # product category, weight, size
category_translation = pd.read_csv(DATA_DIR + "product_category_name_translation.csv")  # category names, Portuguese to English

print("orders:", orders.shape)
print("items:", items.shape)
print("payments:", payments.shape)
print("reviews:", reviews.shape)
print("customers:", customers.shape)
print("sellers:", sellers.shape)
print("products:", products.shape)

"""### Data Cleaning"""

orders.head()

orders.info()

date_cols = ["order_purchase_timestamp","order_approved_at","order_delivered_carrier_date",
             "order_delivered_customer_date","order_estimated_delivery_date"]

for col in date_cols:
  orders[col]=pd.to_datetime(orders[col])

orders.info()

orders["order_id"].duplicated().sum()  # counts how many order_ids repeat

orders["order_status"].value_counts()

# Purchase date should always be earlier than delivery date, flag any row where that's not true

bad_dates = orders[orders["order_delivered_customer_date"] < orders["order_purchase_timestamp"]]
print("Rows where delivery date is before purchase date:", len(bad_dates))

# .copy() tells pandas to make a completely separate copy of this filtered data, rather than just a "view" into the original orders table.

delivered = orders[orders["order_status"] == "delivered"].copy()
print(delivered.shape)

delivered["delivery_days"] = (delivered["order_delivered_customer_date"] - delivered["order_purchase_timestamp"]).dt.days
delivered["delivery_days"].describe()

delivered[delivered["delivery_days"].isnull()][["order_id", "order_purchase_timestamp", "order_delivered_customer_date"]]

delivered=delivered[delivered["delivery_days"].notnull()]
print(delivered.shape)

print("Orders with delivery_days > 60:", (delivered["delivery_days"] > 60).sum())
print("Orders with delivery_days > 100:", (delivered["delivery_days"] > 100).sum())

delivered = delivered[delivered["delivery_days"] <= 60]
print(delivered.shape)



"""***<font size="5" color="cyan"> Hypothesis 1: "Orders delivered after the estimated delivery date receive lower review scores than orders delivered on time."</font>***

"""

delivered["delay_days"] = (delivered["order_delivered_customer_date"] - delivered["order_estimated_delivery_date"]).dt.days

delivered["is_late"] = delivered["delay_days"] > 0

delivered["is_late"].value_counts()

reviews.head()

reviews["review_creation_date"]=pd.to_datetime(reviews["review_creation_date"])

# keep only the latest review per order (some orders have multiple reviews)

reviews_clean = (
    reviews.sort_values("review_creation_date").drop_duplicates(subset="order_id", keep="last")
    [["order_id", "review_score"]])

print(reviews_clean.shape)

# add review_score to our delivered orders table, matching on order_id

delivered = delivered.merge(reviews_clean, on="order_id", how="left")

print(delivered.shape)
print(delivered["review_score"].isnull().sum())  # check how many delivered orders have no review

delivered.columns.tolist()

# On-time (False), Late (True)

delivered.groupby("is_late")["review_score"].mean()

"""## Mann-Whitney U test"""

# statistical test: is the review score difference between late vs on-time orders real, or random chance?

late_scores = delivered[delivered["is_late"] == True]["review_score"].dropna()
ontime_scores = delivered[delivered["is_late"] == False]["review_score"].dropna()

stat, p_value = stats.mannwhitneyu(late_scores, ontime_scores, alternative="less")   # stat and p_value are just variable names. stats.mannwhitneyu() is the actual test function from scipy
print("U statistic:", stat)
print("p-value:", p_value)

# bootstrap confidence interval for the review score gap (on-time minus late)
np.random.seed(42)  # makes results reproducible

bootstrap_gaps = []

for i in range(1000):
    late_sample = np.random.choice(late_scores, size=len(late_scores), replace=True)
    ontime_sample = np.random.choice(ontime_scores, size=len(ontime_scores), replace=True)
    gap = ontime_sample.mean() - late_sample.mean()
    bootstrap_gaps.append(gap)

lower = np.percentile(bootstrap_gaps, 2.5)
upper = np.percentile(bootstrap_gaps, 97.5)

print("Observed gap:", ontime_scores.mean() - late_scores.mean())
print("95% confidence interval:", lower, "to", upper)

"""<font color='yellow'>
Late orders received noticeably lower review scores than on-time orders (average 2.28 vs 4.29 out of 5). A Mann-Whitney U test confirmed this difference is statistically significant (p < 0.001), meaning it is very unlikely to be due to random chance. This is one of the strongest patterns in the dataset, confirming that delivery timeliness has a major impact on customer satisfaction.</font>
"""

# boxplot: review score distribution for late vs on-time orders
plt.figure(figsize=(8, 6))

sns.boxplot(data=delivered, x="is_late", y="review_score", palette=[color_good, color_bad])

plt.title("Review Score Distribution: Late vs On-Time Orders")
plt.xlabel("Order Was Late")
plt.ylabel("Review Score")
plt.show()

"""***<font size="5" color='Cyan'>Hypothesis 2: Orders where the seller and customer are in different states take longer to deliver than same-state orders.</font>***"""

# add customer_state to our delivered orders table
delivered = delivered.merge(customers[["customer_id", "customer_state"]], on="customer_id", how="left")

print(delivered.shape)
print(delivered["customer_state"].isnull().sum())

# attach seller_state to each item row, by looking up the seller's state

items_with_seller=items.merge(sellers[["seller_id","seller_state"]],on="seller_id",how="left")

print(items_with_seller.shape)

# for each order, find the most common seller_state among its items, and count how many unique sellers were involved

order_seller_info = items_with_seller.groupby("order_id").agg(
    main_seller_state=("seller_state", lambda x: x.mode()[0] if not x.mode().empty else None),
    n_sellers=("seller_id", "nunique")
).reset_index()

print(order_seller_info.shape)

order_seller_info.head()

# add seller state info to our delivered orders table

delivered = delivered.merge(order_seller_info,on="order_id",how="left")

print(delivered.shape)
print(delivered["main_seller_state"].isnull().sum())

# flag whether seller and customer are in different states(True=diff states,False=Same state)

delivered["cross_state"] = delivered["customer_state"] != delivered["main_seller_state"]

delivered["cross_state"].value_counts()

delivered.groupby("cross_state")["delivery_days"].mean()

"""Cross-state orders take almost double the time, roughly 7 extra days on average. This makes intuitive sense too, shipping within the same state is naturally faster than crossing state borders across Brazil's large geography."""

# statistical test: is the delivery time difference between cross-state vs same-state orders real, or random chance?

cross_state_days = delivered[delivered["cross_state"] == True]["delivery_days"].dropna()
same_state_days = delivered[delivered["cross_state"] == False]["delivery_days"].dropna()

stat, p_value = stats.mannwhitneyu(cross_state_days, same_state_days, alternative="greater")
print("U statistic:", stat)
print("p-value:", p_value)

"""<font color='yellow'>
Cross-state orders (where the seller and customer are in different states) took noticeably longer to deliver than same-state orders (average 14.38 days vs 7.39 days, nearly double). A Mann-Whitney U test confirmed this difference is statistically significant (p < 0.001).

Verdict: Supported.</font>
"""

# bar chart: average delivery time, cross-state vs same-state orders
plt.figure(figsize=(8, 6))

sns.barplot(data=delivered, x="cross_state", y="delivery_days", palette=[color_good, color_bad])

plt.title("Average Delivery Time: Cross-State vs Same-State Orders")
plt.xlabel("Cross-State Order")
plt.ylabel("Average Delivery Days")
plt.show()

"""***<font size="5" color='Cyan'>Hypothesis 3 : A higher freight cost relative to product price is associated with lower review scores.</font>***"""

items.head()

items_order_info = items.groupby("order_id").agg(
    total_price=("price","sum"),
    total_freight=("freight_value","sum")
).reset_index()

print(items_order_info.shape)

delivered = delivered.merge(items_order_info,on="order_id",how="left")
print(delivered.shape)
print(delivered["total_price"].isnull().sum())

delivered["freight_ratio"] = delivered["total_freight"] / delivered["total_price"]

# count orders where total_price is exactly 0 (would break the ratio)
print("Zero prices:", (delivered["total_price"] == 0).sum())

# count infinite values in freight_ratio (happens if price is 0)
print("Infinite values:", np.isinf(delivered["freight_ratio"]).sum())

# count missing values in freight_ratio
print("Missing values:", delivered["freight_ratio"].isnull().sum())

# summary statistics of freight_ratio
delivered["freight_ratio"].describe()

"""## Spearman correlation test"""

# keep only the two columns needed for H3, and drop rows with a missing review_score
h3_data = delivered[["freight_ratio", "review_score"]].dropna()

# Spearman correlation: do freight_ratio and review_score move in opposite directions?
# corr and p_value are variable names we chose; stats.spearmanr() is the actual test function
corr, p_value = stats.spearmanr(h3_data["freight_ratio"], h3_data["review_score"], alternative="less")

print("Spearman correlation:", corr)
print("p-value:", p_value)

"""<font color='yellow'>
A Spearman correlation test found a statistically significant negative relationship between freight ratio and review score (rho = -0.031, p < 0.001), so orders with higher shipping cost relative to price tend to receive slightly lower reviews. However, the effect is negligible in size, which means freight cost alone is not a meaningful driver of customer satisfaction in this dataset.

Verdict: Weakly supported (statistically significant, but a negligible effect).
</font>

"""

# split freight_ratio into readable bins
delivered["freight_ratio_bin"] = pd.cut(
    delivered["freight_ratio"],
    bins=[0, 0.2, 0.4, 0.6, 1.0, float("inf")],
    labels=["0-0.2", "0.2-0.4", "0.4-0.6", "0.6-1.0", "1.0+"]
)

# average review score per freight ratio bin
freight_bin_scores = delivered.groupby("freight_ratio_bin")["review_score"].mean()
print(freight_bin_scores)

# bar chart: average review score by freight ratio bin
plt.figure(figsize=(8, 6))
sns.barplot(x=freight_bin_scores.index, y=freight_bin_scores.values, color=color_good)

plt.title("Average Review Score by Freight-to-Price Ratio")
plt.xlabel("Freight Ratio")
plt.ylabel("Average Review Score")
plt.show()

"""***<font size="5" color='Cyan'>Hypothesis 4a : ate delivery rates differ significantly across Brazilian states.</font>***"""

del_rate_state = delivered.groupby("customer_state")["is_late"].mean().sort_values(ascending=False)
print(del_rate_state)

delivered["customer_state"].value_counts()

"""# Chi-square test"""

# build a table of counts: each state's orders, split by late vs on-time

state_late_table = pd.crosstab(delivered["customer_state"], delivered["is_late"])
print(state_late_table)

# chi-square test: is lateness related to state, or independent of it?
chi2, p_value, dof, expected = stats.chi2_contingency(state_late_table)

print("Chi-square statistic:", chi2)
print("p-value:", p_value)
print("Degrees of freedom:", dof)

"""<font color='yellow'>
A chi-square test confirmed that late delivery rates differ significantly by state (χ² = 1611.4, p < 0.001). Northeastern states such as Alagoas (20.8%) and Maranhão (17.0%) had the highest late rates, while São Paulo (4.4%), the main hub for sellers, had one of the lowest. This pattern aligns with Hypothesis 2's finding that cross-state orders take longer to deliver, suggesting that distance from major seller hubs is a key driver of late deliveries.

Verdict: Supported.
</font>
"""

# bar chart: late delivery rate by state, sorted highest to lowest
plt.figure(figsize=(14, 6))

sns.barplot(x=del_rate_state.index, y=del_rate_state.values, color=color_bad)

plt.title("Late Delivery Rate by State")
plt.xlabel("State")
plt.ylabel("Late Rate")
plt.xticks(rotation=45)
plt.show()

"""***<font size="5" color='Cyan'>Hypothesis 4b : Late delivery rates are higher during peak demand months, such as November.</font>***"""

# pull the purchase year out of the order date
delivered["purchase_year"] = delivered["order_purchase_timestamp"].dt.year

print(delivered["purchase_year"].value_counts())

# keep only 2017 and 2018 orders, since 2016 is too small a sample (only 264 orders)
delivered_recent = delivered[delivered["purchase_year"].isin([2017, 2018])].copy()

# pull the purchase month out of the order date
delivered_recent["purchase_month"] = delivered_recent["order_purchase_timestamp"].dt.month

# late rate per month
month_late_rate = delivered_recent.groupby("purchase_month")["is_late"].mean().sort_values(ascending=False)
print(month_late_rate)

# build a table of counts: each month's orders, split by late vs on-time
month_late_table = pd.crosstab(delivered_recent["purchase_month"], delivered_recent["is_late"])

# chi-square test: is lateness related to month, or independent of it?
chi2, p_value, dof, expected = stats.chi2_contingency(month_late_table)

print("Chi-square statistic:", chi2)
print("p-value:", p_value)
print("Degrees of freedom:", dof)

"""<font color='yellow'>
A chi-square test confirmed that late delivery rates differ significantly by month (χ² = 2503.2, p < 0.001). November did show an elevated late rate (12.1%), the second-highest of the year, consistent with increased order volume around Black Friday. However, March had the highest late rate overall (14.7%), suggesting that factors beyond the Black Friday shopping surge, which Olist may already prepare logistics capacity for, also affect delivery reliability in certain months.

Verdict: Partially supported. Month has a significant effect on late delivery rates, but November is not the single worst-performing month.
</font>
"""

# order months calendar-wise (not sorted by rate), and prepare colors
month_order = list(range(1, 13))
month_rates_ordered = month_late_rate.reindex(month_order)

month_names = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]

# highlight March and November specifically, rest in neutral color
bar_colors = [color_bad if m in [3, 11] else color_good for m in month_order]

plt.figure(figsize=(10, 6))
sns.barplot(x=month_names, y=month_rates_ordered.values, hue=month_names, palette=bar_colors, legend=False)

plt.title("Late Delivery Rate by Month (2017-2018)")
plt.xlabel("Month")
plt.ylabel("Late Rate")
plt.show()

"""***<font size="5" color='Cyan'>Hypothesis 5 : Customers whose first order arrives late are less likely to place a second order than customers whose first order arrives on time.</font>***"""

# add customer_unique_id to our delivered orders table (tracks the same person across orders)
delivered = delivered.merge(customers[["customer_id", "customer_unique_id"]], on="customer_id", how="left")

print(delivered.shape)
print(delivered["customer_unique_id"].isnull().sum())

first_orders = delivered.sort_values("order_purchase_timestamp").drop_duplicates(subset="customer_unique_id", keep="first")
print(first_orders.shape)

# count how many orders each customer placed in total
customer_order_counts = delivered.groupby("customer_unique_id")["order_id"].count().reset_index()
customer_order_counts.columns = ["customer_unique_id", "total_orders"]

print(customer_order_counts.shape)
print(customer_order_counts["total_orders"].value_counts())

# combine each customer's first-order lateness with their total order count
customer_summary = first_orders[["customer_unique_id", "is_late"]].merge(
    customer_order_counts, on="customer_unique_id", how="left"
)

# flag customers who placed more than one order
customer_summary["is_repeat_customer"] = customer_summary["total_orders"] > 1

print(customer_summary.shape)
customer_summary.head()

# compare repeat purchase rate: customers whose first order was late vs on-time
customer_summary.groupby("is_late")["is_repeat_customer"].mean()

# build a table of counts: late vs on-time first order, split by repeat vs one-time customer
late_repeat_table = pd.crosstab(customer_summary["is_late"], customer_summary["is_repeat_customer"])
print(late_repeat_table)

# chi-square test: is repeat purchase behavior related to whether the first order was late?
chi2, p_value, dof, expected = stats.chi2_contingency(late_repeat_table)

print("Chi-square statistic:", chi2)
print("p-value:", p_value)
print("Degrees of freedom:", dof)

"""<font color='yellow'>
Customers whose first order arrived late had a slightly lower repeat purchase rate (2.55%) than customers whose first order was on time (3.03%). A chi-square test found this difference to be statistically significant, though only marginally (χ² = 4.37, p = 0.037). Given the small effect size and borderline significance, this result should be interpreted cautiously, delivery lateness on a single order does not appear to be a strong standalone driver of customer churn in this dataset, though it may contribute alongside other factors.

Verdict: Weakly supported (borderline significance, small effect).
</font>
"""

# bar chart: repeat purchase rate, late vs on-time first order
plt.figure(figsize=(8, 6))

sns.barplot(data=customer_summary, x="is_late", y="is_repeat_customer", hue="is_late", palette=[color_good, color_bad], legend=False)

plt.title("Repeat Purchase Rate: Late vs On-Time First Order")
plt.xlabel("First Order Was Late")
plt.ylabel("Repeat Purchase Rate")
plt.show()

"""***<font size="5" color='cyan'> Seller and Category Performance: Where Are Late Deliveries Concentrated? </font>***"""

# bring order-level is_late into the item-level table (connects seller info with lateness)
items_with_late = items_with_seller.merge(delivered[["order_id", "is_late"]], on="order_id", how="left")

print(items_with_late.shape)
print(items_with_late["is_late"].isnull().sum())

# drop items whose order wasn't in our cleaned delivered dataset
items_with_late_clean = items_with_late.dropna(subset=["is_late"])

# calculate late rate and item count per seller
seller_performance = items_with_late_clean.groupby("seller_id").agg(
    late_rate=("is_late", "mean"),
    n_items=("is_late", "count")
).reset_index()

print(seller_performance.shape)
seller_performance.head()

# keep only sellers with enough volume to trust their late rate (20+ items)
seller_performance_reliable = seller_performance[seller_performance["n_items"] >= 20]

# sort to find the worst-performing sellers
worst_sellers = seller_performance_reliable.sort_values("late_rate", ascending=False)

print(worst_sellers.shape)
worst_sellers.head(10)

"""<font color='yellow'> Additional Analysis: Seller Performance

Among sellers with at least 20 items sold (880 sellers), late delivery rates varied widely. The worst-performing seller had a 50% late rate across 46 items, nearly 8 times the platform-wide average of 6.5%. The 10 worst sellers all exceeded a 23% late rate. This suggests that a small number of consistently underperforming sellers may be disproportionately responsible for poor delivery outcomes, and could be targeted directly for review or improvement, rather than Olist needing to address delivery policy platform-wide.</font>
"""